In [536]:
# Importando as bibliotecas necessárias

from sklearn.metrics import classification_report, confusion_matrix

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [537]:
url = "https://raw.githubusercontent.com/v1eira/heart-attack-in/master/heart.csv"

# Nomes das colunas no dataset
columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

# Lendo o csv
dataset = pd.read_csv(url, names=columns, skiprows=1)

In [538]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 13].values

In [539]:
# Função que retorna precisão e recall da matrix
def Scores(matrix):
  tp = matrix[0][0]
  fp = matrix[0][1]
  fn = matrix[1][0]
  tn = matrix[1][1]
  return tp/(tp+fp), tp/(tp+fn)

In [540]:
from sklearn.model_selection import KFold
 
# Função que retorna a matriz de confusão e suas informações
def makeConfusionMatrix(X, classifier):
  kf = KFold(n_splits=5)
 
  all_matrices = []
  avg_accuracy = 0
 
  for train_index, test_index in kf.split(X):
 
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    
    mat = confusion_matrix(y_test, y_pred)
    all_matrices.append(mat)
 
    clf = classification_report(y_test, y_pred, output_dict=True, zero_division=1)
    avg_accuracy += clf['accuracy']
  # for
 
  confMatrix = all_matrices[0]
  for i in range(len(all_matrices)):
    if i > 0:
      confMatrix += all_matrices[i]
    # if
  # for
 
  scores = Scores(confMatrix)
  
  print(confMatrix, '\n')
  print('Média das acurácias: ', (avg_accuracy / 5))
  print('Precisão: ', scores[0])
  print('Recall: ', scores[1])
 
# makeConfusionMatrix

In [541]:
from sklearn.neighbors import KNeighborsClassifier

# Neighbors = 3
classifier = KNeighborsClassifier(n_neighbors=3)
makeConfusionMatrix(X, classifier)

[[56 82]
 [70 95]] 

Média das acurácias:  0.4975409836065573
Precisão:  0.4057971014492754
Recall:  0.4444444444444444


In [542]:
# Neighbors = 5
classifier = KNeighborsClassifier(n_neighbors=5)
makeConfusionMatrix(X, classifier)

[[53 85]
 [67 98]] 

Média das acurácias:  0.4973770491803279
Precisão:  0.38405797101449274
Recall:  0.44166666666666665


In [543]:
# Neighbors = 7
classifier = KNeighborsClassifier(n_neighbors=7)
makeConfusionMatrix(X, classifier)

[[ 49  89]
 [ 65 100]] 

Média das acurácias:  0.49065573770491816
Precisão:  0.35507246376811596
Recall:  0.4298245614035088


In [544]:
# Neighbors = 9
classifier = KNeighborsClassifier(n_neighbors=9)
makeConfusionMatrix(X, classifier)

[[ 51  87]
 [ 63 102]] 

Média das acurácias:  0.5038797814207651
Precisão:  0.3695652173913043
Recall:  0.4473684210526316
